import pandas as pd
import matplotlib.pyplot as plt
import mysql.connector
import os



# Establish a connection to the database
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Aachal@156",
    database="healthcare_db"
)

# Query data to analyze age distribution
query1 = """
    SELECT YEAR(CURDATE()) - YEAR(birthdate) AS age, 
           COUNT(*) AS count 
    FROM patients 
    GROUP BY age 
    ORDER BY age;
"""
df = pd.read_sql(query1, conn)

# Load the CSV reports generated by generate_report.py
allergies_df = pd.read_csv('../data/common_allergies_report.csv')
medications_df = pd.read_csv('../data/medications_report.csv')
immunizations_df = pd.read_csv('../data/immunizations_report.csv')
devices_df = pd.read_csv('../data/devices_report.csv')

# Visualizing common allergies
plt.figure(figsize=(10, 20))
plt.bar(allergies_df['description'], allergies_df['count'], color='lightgreen')
plt.xlabel('Allergy Description')
plt.ylabel('Number of Patients')
plt.title('Common Allergies')
plt.xticks(rotation=90)
plt.grid(axis='y')
plt.show()

# Visualizing common medications
plt.figure(figsize=(10, 20))
plt.bar(medications_df['description'], medications_df['count'], color='lightcoral')
plt.xlabel('Medication Description')
plt.ylabel('Number of Patients')
plt.title('Common Medications')
plt.xticks(rotation=90)
plt.grid(axis='y')
plt.show()

# Visualizing immunizations
plt.figure(figsize=(10, 20))
plt.bar(immunizations_df['patient'], immunizations_df['immunization_count'], color='lightskyblue')
plt.xlabel('Patient ID')
plt.ylabel('Number of Immunizations')
plt.title('Immunization Count by Patient')
plt.xticks(rotation=90)
plt.grid(axis='y')
plt.show()

# Visualizing device usage
plt.figure(figsize=(10, 20))
plt.bar(devices_df['description'], devices_df['count'], color='lightgoldenrodyellow')
plt.xlabel('Device Description')
plt.ylabel('Number of Patients')
plt.title('Device Usage')
plt.xticks(rotation=90)
plt.grid(axis='y')
plt.show()






# Visualize patient age distribution
plt.figure(figsize=(10, 6))
plt.bar(df['age'], df['count'], color='skyblue')
plt.xlabel('Age')
plt.ylabel('Number of Patients')
plt.title('Patient Age Distribution')
plt.grid(axis='y')
plt.show()



conn.close()
